name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag ${{ vars.TENGXUNYUN }}/${{ vars.NAMESPACE }}/${{ vars.IMAGES }}:$(date +%s)
    - name: Push docker image
      run: |
        docker login ${{ vars.TENGXUNYUN }} --username=${{ secrets.USERNAME }}
        echo ${{ secrets.TENGXUNYUN }}
        docker push ${{ vars.TENGXUNYUN }}/${{ vars.NAMESPACE }}/${{ vars.IMAGES }}:$(date +%s)
