name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install and Build
      run: |                               # 步骤运行的命令
        yarn install
        yarn build
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag ${{ vars.TENGXUNYUN }}/${{ vars.NAMESPACE }}/${{ vars.IMAGES }}:$(date +%s)
