name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_URL: ${{ vars.TENGXUNYUN }}/${{ vars.NAMESPACE }}/${{ vars.IMAGES }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag ${{ env.IMAGE_URL }}:$(date +%s)
    - name: Push docker image
      run: |
        docker login --username ${{ secrets.USERNAME }} -p ${{ secrets.TENGXUNYUN }} ${{ vars.TENGXUNYUN }}
    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push ${{ env.IMAGE_URL }}:$(date +%s)
